# Docker Compose file for Notes API application
version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    # These settings are overridden by .env.docker
    # No dependency on local db when using Aurora
    networks:
      - app-network
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    command: ["/app/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Local database service removed - using actual Aurora database

networks:
  app-network:

# No volumes needed for external database