"""test_permissions

Revision ID: 20510c1c4e3d
Revises: 9f22b5e5a123
Create Date: 2025-09-18 16:06:35.157116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20510c1c4e3d'
down_revision = '9f22b5e5a123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###